WebFrontToBack/Models/RecentWorks.cs
using System.ComponentModel.DataAnnotations;

namespace WebFrontToBack.Models
{
    public class RecentWorks
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Bos ola bilmez"), MaxLength(50, ErrorMessage = "Uzunluq maks 50 simvol olmalidir")]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string ImagePath { get; set; }
    }
}

WebFrontToBack/Areas/Admin/Controllers/RecentWorksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebFrontToBack.Areas.Admin.ViewModels;
using WebFrontToBack.DAL;
using WebFrontToBack.Models;
using WebFrontToBack.Utilities.Extensions;

namespace WebFrontToBack.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RecentWorksController : Controller
    {
        private readonly AppDbContext _Context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public RecentWorksController(AppDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _Context = context;
            _webHostEnvironment = webHostEnvironment;

        }
        public async Task<IActionResult> Index()
        {
            ICollection<RecentWorks> recentWorks =await _Context.RecentWorks.ToListAsync();
            return View(recentWorks);
        }
        [HttpGet]
         public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRecentWorksVM recentWorks)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (!recentWorks.Photo.CheckContentType("image/"))
            {
                ModelState.AddModelError("Photo", $"{recentWorks.Photo.FileName} type must be image type");
                return View();
            }
            if (!recentWorks.Photo.CheckFileSize(400))
            {
                ModelState.AddModelError("Photo", $"{recentWorks.Photo.FileName} file type must be size less than 200kb");
                return View();
            }
            string root = Path.Combine
                (_webHostEnvironment.WebRootPath, "assets", "img");

            string fileName = await recentWorks.Photo.SaveAsync(root);



            RecentWorks recentWorks1 = new RecentWorks()
            {
                Name = recentWorks.Name,
                ImagePath = fileName,
                Description = recentWorks.Description
            };
            await _Context.RecentWorks.AddAsync(recentWorks1);  
            await _Context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int Id)
        {
            RecentWorks? recentWorks = _Context.RecentWorks.Find(Id);
            if (recentWorks == null)
            {
                return NotFound();
            }
            return View(recentWorks);
        }
        [HttpPost]
        public IActionResult Update(RecentWorks recentWorks)
        {
            RecentWorks? editedRecentWorks = _Context.RecentWorks.Find(recentWorks.Id);
            if (editedRecentWorks == null)
            {
                return NotFound();
            }
            editedRecentWorks.Name = recentWorks.Name;
            _Context.RecentWorks.Update(editedRecentWorks);
            _Context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            RecentWorks? recentWorks = _Context.RecentWorks.Find(id);
            if (recentWorks == null)
            {
                return NotFound();
            }
            string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "assets", "img", recentWorks.ImagePath);
            if (System.IO.File.Exists(imagePath))
            {
                System.IO.File.Exists(imagePath);
            }
            _Context.RecentWorks.Remove(recentWorks);
            _Context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

WebFrontToBack/Areas/Admin/Views/RecentWorks/Create.cshtml
@model CreateRecentWorksVM;

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Works">
                    <span class="text text-danger" asp-validation-for="Name"></span>
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" placeholder="Profession">
                    <span class="text text-danger" asp-validation-for="Description"></span>
                    <label asp-for="Photo"></label>
                    <input asp-for="Photo" class="form-control" placeholder="Photo">
                    <span class="text text-danger" asp-validation-for="Photo"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Create</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>

            </form>
        </div>
    </div>
</div>

WebFrontToBack/Areas/Admin/Views/RecentWorks/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

WebFrontToBack/Areas/Admin/Views/RecentWorks/Index.cshtml
@model ICollection<RecentWorks>
@{
    int count = 1;
}
<div class="d-flex justify-content-end mb-2">
    <a class="btn btn-success text-light" asp-area="Admin" asp-controller="RecentWorks" asp-action="Create">Create Works</a>
</div>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                Number
                            </th>
                            <th>
                                Works Name
                            </th>

                        </tr>
                    </thead>
                    <tbody>

                        @foreach (RecentWorks item in Model)
                        {
                            <tr>
                                <td> @count</td>

                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    <a class="btn btn-primary text-light">Detail</a>
                                    <a class="btn btn-warning text-light" asp-area="Admin" asp-controller="RecentWorks" asp-action="Update" asp-route-Id="@item.Id">Update</a>
                                    <a class="btn btn-danger text-light" asp-area="Admin" asp-controller="RecentWorks" asp-action="Delete" asp-route-Id="@item.Id">Delete</a>
                                </td>
                            </tr>
                            count++;
                        }

                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

WebFrontToBack/Areas/Admin/Views/RecentWorks/Update.cshtml
@model RecentWorks;

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">

            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Works">
                    <span class="text text-danger" asp-validation-for="Name"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2 text-light">Edit</button>
                <button class="btn btn-light" asp-action="Index">Go back</button>
            </form>
        </div>
    </div>
</div>